### ISSUE TITLE
Suggestion to improve stability on power up

### ISSUE THREAD

**Issue by andymcca** [mac2612/lf2000_kernel#1]
https://github.com/mac2612/lf2000_kernel/blob/188561f7b1f512537dd9e343c0d707896e820410/drivers/input/touchscreen/lfp100.c#L1114

I briefly discussed this with Mac - this is a hacky delay to allow the overclock to settle down before configuring the touchscreen.  I think it might need to be longer to stop the GS in particular hanging on the Leapfrog screen on startup around 50% of the time.  Could you try increasing from 100 to 200 in the code?  I can't seem to do a PR.

**Comment by DCFUKSURMOM** [comment]
ill take a look at it

**Comment by andymcca** [comment]
Closing - meant to open this on the Overclock/RT fork.

**Comment by DCFUKSURMOM** [comment]
I saw it pop up under issues when looking at my commit history lol.
